### ISSUE TITLE
Routing by http method results in "405 Method Not Allowed"

### ISSUE THREAD

**Issue by localvar** [easegress-io/easegress#400] opened 2021-12-06 09:50 UTC
**Describe the bug**
Routing by HTTP method results in "405 Method Not Allowed"

**To Reproduce**
1. Config an HTTP server with routing rules like below:
```yaml
- paths:
    - pathPrefix: /hello/
      backend: hello-get
      methods: [GET]
    - pathPrefix: /hello/
      backend: hello-delete
      methods: [DELETE]
```
2. Send a request to the HTTP server with method `DELETE` and path `/hello/1`
3. Easegress response with `HTTP/1.1 405 Method Not Allowed`

**Expected behavior**
The request was forwarded to the backend service successfully.

**Comment by xxx7xxxx** [comment] 2021-12-07 04:05
Some research about whether other gateway products support method-level routing:

1. Nginx: support it by using `if-clause`[1].
2. Trafeik: support it by designing a DSL[2].
3. APISIX: not support[3].
4. Caddy: support it by its own config grammar[4].
5. Kubernetes Ingress: not support[5].
6. Envoy: support by reusing header matching[6]

My thoughts about the feature conclude 2 points:

1. If we support it in a natural way, it will be a redesign of the route. We can see all products above supporting method routing are leveraging DSL (even in yaml config file). Cause flexible routing rules are complex, so simple grammar can hardly cover it. On the other hand, APISIX does not support it because of performance I guess, Kubernetes does not support it either because it won't introduce so much complexity to a general service traffic entry description.
2. If we support it in a quick way, the envoy is an interesting object to study. It just use a special header to represent the method. The headers routing rules for now in Easegress could naturally introduce it because the current mechanism of headers matching is that it will fall through the next rule if there are headers but not matching.

[1] https://serverfault.com/a/152764/235402 
[2] https://doc.traefik.io/traefik/routing/routers/#rule
[3] https://apisix.apache.org/docs/apisix/architecture-design/router/
[4] https://caddyserver.com/docs/caddyfile/matchers#method
[5] https://kubernetes.io/docs/concepts/services-networking/ingress/
[6] https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-headermatcher

**Comment by mydoors88** [comment] 2021-12-07 08:23
I think it is more powerful providing the DSL to define the route rule.The concern on the performance maybe be resolved with the cache mechanism.

**Comment by xxx7xxxx** [comment] 2021-12-07 08:26
Static APIs are suitable to cache, but dynamic APIs are not. So the cache is not the performance-saving straw as a general gateway.

**Comment by mydoors88** [comment] 2021-12-07 09:50
Is it possible to cache the small set of route path?the high frequency of route path accessed will  find in the fastest way. So it will cache result of computing the route path with regex formula.

**Comment by xxx7xxxx** [comment] 2024-01-28 03:39
It's fixed by new Search[1]

[1] https://github.com/easegress-io/easegress/blob/25e424080a161b70f6e987198a0ee5412ad95a73/pkg/object/httpserver/routers/ordered/router.go#L134

**Closed by xxx7xxxx** 2024-01-28 03:39 UTC
Labels: enhancement
